### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by Baptiste-J** [nirfaster/NIRFASTer#1]
Hello,
I am trying to use NIRFASTer with the GPU solver. After updating the drivers of my graphics card to the latest version and installing the latest Nvidia GPU computing toolkit, I am still running into the following error: 
> Invalid MEX-file '\NIRFASTer\toolbox\mex\FD\get_field_FD_CUDA.mexw64': Missing
dependent shared libraries:
'cusparse64_10.dll' required by '\NIRFASTer\toolbox\mex\FD\get_field_FD_CUDA.mexw64'
'cublas64_10.dll' required by '\NIRFASTer\toolbox\mex\FD\get_field_FD_CUDA.mexw64'. 

I did a search for the missing files and I cannot find them on my computer, I only have the more recent ones: cusparse64_11.dll and cublas64_11.dll

I know I can probably solve this by installing an older version of the GPU computing toolkit, but I thought I should still mention this. 

Thanks

**Comment by swojtkiewicz** [comment]
Hi Baptiste

Thanks!
Looks like I forgot to update the **.dll* files after recompiling on CUDA 10.1 Toolkit.
Should be fixed now. Please download the code again. I have swapped the DLLs to the correct version: **_10.dll*
Please let me know it this still does not work. 

BTW: In theory, all should work without the CUDA Toolkit installed. Just the GPU drivers.

Stan

**Comment by Baptiste-J** [comment]
Hi Stan,
Thanks for the quick response! I just tried with the new code and unfortunately I still get an error.

> Invalid MEX-file '\NIRFASTer\toolbox\mex\FD\get_field_FD_CUDA.mexw64': Missing dependent shared libraries:
'cublasLt64_10.dll' required by '\NIRFASTer\toolbox\mex\FD\cublas64_10.dll-> \NIRFASTer\toolbox\mex\FD\get_field_FD_CUDA.mexw64'

Initially the function isCUDA did not detect any GPU on my computer, that's when I noticed that the drivers were quite old so I updated the Nvidia GPU river (I currently have the version 451.48) without installing the CUDA toolkit. With the new driver, the GPU was detected by isCUDA, but I got the error of the missing .dll so I installed the CUDA toolkit and since it did not fix the error I  raised  this issue.

Thanks!
Baptiste

**Comment by swojtkiewicz** [comment]
Hi

Great! Looks like my solution works. There is still a DLL missing. I have uploaded this third missing DLL (cublasLt64_10.dll) just now.
Try if this works now. Let me know if this works or other DDLs are missing as well.

Thanks for testing,
Stan

**Comment by Baptiste-J** [comment]
Hi Stan,

I just tested and it is working now! Thank you very much for your help.

Baptiste

**Comment by swojtkiewicz** [comment]
Hi Baptiste

Cool! Happy to help. 
Closing this issue.

Stan
